### ISSUE TITLE
-eI bug

### ISSUE THREAD

**Issue by jackkamm** [scrm/scrm#102]
Consider a demography where population 1 is sampled at 0, population 2 is sampled at t2, and population 1 and 2 join at tJ.

If t2 > tJ, scrm can sometimes give an error of non-coalescence.
```
scrm 4 1 -t 1.0 -I 2 2 0 -ej 1.0 1 2 -eI 3.5 0 2
835262454

//
Error: Lines did not coalescence.
The lines were in populations 2 and 1.
You should add on opportunity for migration between these populations.

Try 'scrm --help' for more information.
```
But sometimes scrm works for the exact same demography with a different seed.
```
scrm 4 1 -t 1.0 -I 2 2 0 -ej 1.0 1 2 -eI 3.5 0 2
403661958

//
segsites: 7
positions: 0.0262532 0.065055 0.0799752 0.0866165 0.331099 0.635995 0.890105 
1000000
0111110
0000001
0000000
```

**Comment by shajoezhu** [comment]
@paulstaab I think we should add checks for input. in this example, we should check the number of samples 4 != 2+0

**Comment by jackkamm** [comment]
But there are 4 samples here. 2 are archaic (-eI).

**Comment by shajoezhu** [comment]
I see. ok, my bad.

**Comment by paulstaab** [comment]
Thanks for the report, this definitely is a bug in scrm. It fails to calculate the correct coalescence rate if the archaic leaf is further in the past than the MRCA of the two contemporary nodes. If the MRCA is further in the past, everything works correctly.

**Comment by paulstaab** [comment]
Oh I see, the -ej event never gets executed in this scenario because the algorithm first stops when the root for the two contemporary samples is found (in population 1), and then continues directly at the time that the first archaic node is added. That is an edge case that I did not anticipate so far, thanks for report it! We actually need to account for the time after the root in that case. That is not trivial to implement, and will take some time.

**Comment by paulstaab** [comment]
But that also implies that scrm can actually produce false results without throwing an error, because it might ignore for example migration events.

**Comment by jackkamm** [comment]
Thanks! It is indeed an unusual edge case, and I believe it can be avoided by specifying the demography in a different way. For example,
```
scrm 4 1 -t 1.0 -I 1 2 -eI 3.5 2
```
seems to work, and is a more natural way to specify the exact same demography. However it would be nice for this edge case to just work (I encountered it while programmatically trying lots of different values for t2, usually t2<tJ, but occasionally t2>tJ would occur).

**Comment by paulstaab** [comment]
Yes that true for your case, but for example

```
scrm 4 1 -t 1.0 -eM 10.0 0.5 -I 2 2 0 -eI 20.0 2 0
```

would work without error in almost all cases, but the change of migration of the MRCA of the two contemporary samples would be ignored for the time from 10 to 20.

Anyway a fix is easier than I anticipated, I'll submit a PR soon.

**Comment by paulstaab** [comment]
The fixed version 1.7.1 is now available on [scrm's website](https://scrm.github.io).

@kdmurray91 : Do you want me to ping you on new releases of scrm?

@jeromekelleher : How is the anaconda package updated? Do you want to do that, or should I take care of it?

**Comment by kdmurray91** [comment]
@paulstaab It doesn't hurt, but so long as you are diligent with pushing git tags for each release this will be picked up by debian's upstream watch mechanism.

**Comment by jeromekelleher** [comment]
@paulstaab, I've made the PR to update scrm:

https://github.com/bioconda/bioconda-recipes/pull/1131

I'm happy to update the packages if you ping me, or you can update the recipe yourself if you like (as you can see it's pretty easy!).

**Comment by paulstaab** [comment]
@kdmurray91 That's nice! Tags are required to trigger the build of the different release packages. I is unlikely that I'll forget them...

@jeromekelleher Thanks, I think I can try myself next time :-)
