### ISSUE TITLE
-M is ignored if specified before -I

### ISSUE THREAD

**Issue by terhorst** [scrm/scrm#108]
If `-M` is specified before `-I` it seems to have no effect. The following commands take the minimum TMRCA over 1000 repetitions.

```
scrm 2 1000 -I 2 1 1 -M 100 -ej 5 2 1 -L | grep time: | cut -f2 | sort -n | head -1 # Result: ~0
scrm 2 1000 -M 100 -I 2 1 1 -ej 5 2 1 -L | grep time: | cut -f2 | sort -n | head -1 # Result: ~5
```

Maybe you should just require that `-I` comes before any other demography-related parameters. I am running v1.7.2.

**Comment by paulstaab** [comment]
Good catch, thanks for the report. I agree that we should require the `-I` to be first.
