### ISSUE TITLE
allow `-f` option?

### ISSUE THREAD

**Issue by petrelharp** [scrm/scrm#109]
Enhancement request: implement the convenient option that `ms` has, that allows the parameters to be specified in an external file, with the `-f (filename)` option.

My demographic scenarios are complicated enough that I can't do it on the command line.

**Comment by paulstaab** [comment]
Good point. Shouldn't be difficult and I have encountered problems with character limits on the command line myself before. I plan to integrate this into the next release.

**Comment by paulstaab** [comment]
Realistically, this is not going to happen anymore. If anyone is interested in providing a PR for this, I am happy to review and merge it.

I am closing this issue for now.
