### ISSUE TITLE
Fuller description of "-0" option

### ISSUE THREAD

**Issue by ejewett** [scrm/scrm#113]
Hi,

First off, thanks for making a great simulator! I've been using it a lot.

I was wondering if you could provide a fuller description of the oriented forest output from scrm. The wiki gives the following tree as an example:

{"length":70, "parents":[5,6,7,5,6,7,0], "node_times":[0,0,0,0,0.328647,0.559424,0.88458]} 

and the description says "in the first tree, node 1 and node 4 have node 6 as parent, which itself has the root node 7 as parent. The node_times vector gives the time for each node."

Is this a typo? Do you mean that nodes 1 and 4 both have node 5 as a parent, which itself has node 6 as a parent?

I ran some examples to try to figure this out and I get results that make sense to me if the "parents" vector has the following format for a tree with n leaves:

[node_1_parent, node_2_parent, ... , node_{2*n-2}_parent, 0]

while the "node_times" vector has the format

[node_1_time, node_2_time, ..., node_{2*n-1}_time]

Question 2:

If the format I've listed is correct, this means that the parent of the root node is always listed as 0?

Question 3:

I ran some simulations with 5 populations, each with a single lineage, and the topology ((1,5),4),(2,3)) and very long skinny branches to avoid incomplete lineage sorting. When I do this, scrm outputs the "parents" vector I would expect, given the numbering scheme above (namely, something like "[6,8,8,7,6,7,9,9,0]"). But I also get the completely compatible, but different numbering scheme "[7,6,6,8,7,9,8,9,0]."  So it looks like different trees use different numbers for the internal nodes?

Thanks!

Ethan

**Comment by shajoezhu** [comment]
Hey Ethan

Long time no see! 
Q1. It is a typo, me reading the tree, it should have a topology of (((1,4)5,2)6,3)7. One way to check this is to run scrm with the same seed twice, each time use different output flag "-O" and "-T"

Q2. Yes.

Q3. Yes, that is possible. Even though both trees have the same topology. But they should represent very different coalescent scenario. The TMRCA of clades ((1,5),4) and (2,3) should be one higher than the other in the two cases. Could you check the node_times?

Best
Joe

**Comment by ejewett** [comment]
Thanks Joe!

Okay great.

For Q3: yep, the node times are different. For the two trees, I get 

{"length":1, "parents":[6,8,8,7,6,7,9,9,0], "node_times":[0,0,0,0,0,0.54986,5.0483,1.942,7.4222]}
{"length":1, "parents":[7,6,6,8,7,9,8,9,0], "node_times":[0,0,0,0,0,1.942,0.54986,5.0483,7.3791]}

Everything looks good. Thanks!

Ethan

**Comment by paulstaab** [comment]
Hi Ethan,

thanks for pointing this out, I've corrected the wiki article. Seems I was still confused by our discussion whether the arrays should be zero- or one-indexed back then when writing the documentation... 

For Q3:
The sorting of the nodes is basically random at the moment (that was another error in the documentation). Is that a problem for you? Makes spotting identical typologies much harder...

What command did you use to generate the two trees? It it striking that all times but the TMRCA are equal. Could be a bug.

**Comment by ejewett** [comment]
Hi Paul and Joe,

Thanks a bunch for all your help with scrm!

Regarding your question and edit: Yep, that's exactly what happened. The two trees I sent you are right next to each other with a recombination between them (generated using -T and -r), so I would only expect one coalescence time to differ, which is what we see here. So I think it's probably okay!

Here's the input command in case you care, but I think everything looks good to me:

scrm 5 1 -p 5 -O -r 200 1000 -I 5 1 1 1 1 1 -n 1 0.282467532468 -n 2 0.175324675325 -n 3 0.0941558441558 -n 4 0.175324675325 -n 5 0.256493506494 -eps 0.230846774194 5.0 1.0 0.0 -eps 1.93951612903 3.0 2.0 0.0 -eps 4.70262096774 4.0 1.0 0.0 -eps 7.26209677419 2.0 1.0 0.0


It's totally fine with me that the node labels switch. True that it might make it a little harder to parse the trees, but that's okay for me at the moment. I just wanted to check to make sure I wasn't missing something.

Thanks for putting together a really nice simulator!

All the best,

Ethan

**Comment by paulstaab** [comment]
I made a small change in f5717f551a45d83474e44525e850394c3e8b84b0 that should make the label consistent as long as the topology does not change.

**Comment by ejewett** [comment]
Okay sounds great! I'll check it out.

**Comment by paulstaab** [comment]
I'll close this issue for now. 

Best,
Paul
