### ISSUE TITLE
Order of samples in output

### ISSUE THREAD

**Issue by alanrogers** [scrm/scrm#116]
The documentation doesn't specify the order in which samples are printed in the output. Presumably, samples from population 1 are printed before those from population 2, and so on. But what happens when population 1 has several samples of different ages, as specified in -eI arguments? Are younger samples printed first? Or last? Or are samples printed in the order in which the -I and -eI arguments appear on the command line?

Thanks, Alan Rogers

P.S. I just read the code, and it appears that within each population, samples are output in the order in which they are defined by -I and -eI arguments. It appears that -I needs to come first on the command line, so samples at time 0 will be printed first. After that, -eI arguments can come in any order, and the order in which they appear determines the order of samples in output. Do I have this right?

**Comment by paulstaab** [comment]
Thanks for bringing this up, I thought we had that written down somewhere. That does not seem to be the case. Sorry!

What you inferred from the code is completely correct. 

I just added a [description](https://github.com/scrm/scrm/wiki/Output#output-format) to the documentation.
