### ISSUE TITLE
Allowing higher precision output for positions

### ISSUE THREAD

**Issue by melop** [scrm/scrm#117]
Hello,

I am currently simulating a 70Mb sequence. The position output has been currently limited to 6 digits. This has caused some "collision" of SNP positions. It would be nice if the output position precision can be set by the user, or set to a higher precision.

Best Regards,
Ray

**Comment by shajoezhu** [comment]
Hi @melop 

Use the flag "-p"
  -p <digits>      Specify the number of significant digits used in the output.
                   Defaults to 6.

Best
Joe

**Comment by melop** [comment]
Thanks!

Ray
