### ISSUE TITLE
scrm sometimes produces more segregating sites than the length of the locus

### ISSUE THREAD

**Issue by gveeden** [scrm/scrm#129]
When I specify the length of the locus with the -r flag, I sometimes get more segregating sites than the length of the locus should allow.

Example command:

`scrm 10 1 -t 4 -seed 1111 -N 10000 -r 100 100000`

10 haplotypes.
1 locus.
thetha of 4 --> 4 x 10000 (Ne) x 1e-9 (mutation rate per bp per generation) x 100 000 (length of locus).
Effective population size (Ne) of 10 000.
Initial recombination rate of 100 with a locus length of 100 000.

This produces 113 202 segregating sites for this locus.

Another example:

`scrm 10 1 -t 0.0004 -seed 1111 -N 10000 -r 10 10`

Yields 14 segsites.

In another example that excludes -N:

`scrm 10 1 -t 4 -seed 1111 -r 100 100000`

I get 8 segregating sites.

Do I perhaps not fully understand the length parameter of the -r flag? Or is it being ignored when the effective population size is specified?

**Comment by paulstaab** [comment]
Similar to *ms* and other coalescent simulators, *scrm* always uses an infinite sites model, i.e. there is no concept of sequence length for the mutations. The length parameter of `-r` is only relevant for scaling the recombination rate.

Also, `-N` does not set the effective population size, which is irrelevant for coalescent simulations. It states the size of sub populations only relative to each other.

Best,
Paul

**Comment by gveeden** [comment]
Pardon my ignorance Paul.

Thank you for your response, it proved very helpful.
