### ISSUE TITLE
warning -Wuninitialized at compilation and update to the CRAN

### ISSUE THREAD

**Issue by timflutre** [scrm/scrm#136]
Hello,
I like `scrm` very much, thanks a lot, and use it notably for courses with students. However, it was recently archived by the CRAN because of warnings at compilation ([details](https://cran-archive.r-project.org/web/checks/2021/2021-08-01_check_results_scrm.html)):
```
Found the following significant warnings:
  scrm/summary_statistics/../random/fastfunc.h:91:17: warning: 'y' is used uninitialized [-Wuninitialized]
  scrm/random/fastfunc.h:91:17: warning: 'y' is used uninitialized [-Wuninitialized]
```
Is it simply a matter of adding a line with `double y = 0.0;` and then `y = x;`?
If so, I can make a pull request. And then can you make an update to the CRAN?
Best,
Tim

**Comment by DirkMetzler** [comment]
Sorry that it took a while, but we finally got scrm back to CRAN: https://cran.r-project.org/web/packages/scrm/index.html
May still take a day or two until it is also available through the cran mirrors.
Best,
Dirk

**Comment by timflutre** [comment]
Great, thanks a lot!
