### ISSUE TITLE
Exception handling for sequence length

### ISSUE THREAD

**Issue by shajoezhu** [scrm/scrm#50]
Correct syntax: `scrm 100 1 -t 400 -r 100 1000000 -T`
Incorrect syntax: `scrm 100 1 -t 400 -r 100 1e+06 -T` 

Our program is not currently handling 1e+06 well.

**Comment by paulstaab** [comment]
Yes, good catch. Same is true over all other parameters, I fell over this yesterday when trying to simulate many loci. Think there should be something in the STL for handling this. I should have some time to look into it this weekend.

**Comment by paulstaab** [comment]
scrm 10 1 -r 10 1e5 -t 1
    3320312849
    ---- Model: ------------------------
    Sample size: 10

    At position 0:
     Mutation rate: 2.5e-05
     Recombination rate: inf

    At time 0:
     Population sizes: 5e-05 
    ------------------------------------

Ouch! We should also add a check for finite recombination rate...

**Comment by shajoezhu** [comment]
cool! Thanks Paul! :)

**Comment by shajoezhu** [comment]
BTW, I think this also need to be checked in the R version as well. In particular, R stores number in float by default (? by memory) unless specified as integer. I think fixing this will be valuable for the R API as well.

**Comment by paulstaab** [comment]
Okay, doubles support scientific notation out of the box, but integers don't. I fixed this be first reading in integer values to a double, and then casting to `int`/`size_t` afterwards.

**Comment by shajoezhu** [comment]
:+1:  Great! Thanks Paul
