### ISSUE TITLE
scrm should throw an explicit error if a population has size 0

### ISSUE THREAD

**Issue by paulstaab** [scrm/scrm#52]
Currently scrm throws a number of different downstream errors if a population is equal to zero, e.g.

```
scrm 10 1 -N 0 --seed 15
15

//
Error: Node has no previous node
```

There should be an explicit error because it might not be obvious what is wrong in more complex models.

**Comment by shajoezhu** [comment]
hey @paulstaab , i was wondering what do you think of the idea of having our own class of exceptions scrm, and have two derived exceptions for parsing, and simulation to handle errors?

**Comment by paulstaab** [comment]
@shajoezhu I'm not sure if a user cares about where in our program the error occurred. In the end, almost all error we throw are misspecified models. We catch some errors while parsing (like this one now or missing migration rates) and other during simulation (like infinite coalescences time because of ongoing population shrinkage). I'm not opposed to derive an exceptions class, say for model errors, but right now I don't really see an advantage. What's your opinion here?

**Comment by shajoezhu** [comment]
I don't think there is an immediate need for implementing this. However, I think it would be useful for user in the future. In particular when including scrm as a library. lately, I was involved in a project which used a library that had a bad error handling utility, and caused a bit of headache. a few of my friends have asked about scrm, and they intend to include it as a library. hence, the proposal

**Comment by paulstaab** [comment]
Sounds reasonable. Let's keep this in mind.

2015-04-03 1:49 GMT+02:00 Joe Zhu <notifications@github.com>:
