### ISSUE TITLE
Packaging: Looking for maintainers

### ISSUE THREAD

**Issue by paulstaab** [scrm/scrm#68]
It would be nice to have scrm available in the native installation formats for as many platforms as possible. I don't have time for more Linux packages than provided via the OpenSUSE build service and the Arch package myself, and don't have access to a Mac or PC. Hence, we are looking for maintainers for scrm packages, for example for (but not restricted to):
- Windows (binaries build with the visual studio compiler in an msi package?)
- OS X (ports or brew packages?)
- Debian and derivatives (deb package in the official debian repos)
- Fedora and other rpm based distros

If you are interested in packaging scrm, please feel free to post here, or write an email to `develop (at) paulstaab (dot) de`. Packaging scrm is usually pretty easy, as it has only few dependencies (only a compiler that supports enough C++11 & make, and optionally CppUnit for running the test suite).

**Comment by kdmurray91** [comment]
G'day Paul,

I'm interested in maintaining scrm as an official debian package under the Debian Med team. Do you have existing debian packaging configs?

Cheers,
Kevin

**Comment by paulstaab** [comment]
Hi Kevin,

that's fantastic! Currently, the Debian packages are created using the OpenSUSE build service. The config files are available there: 

https://build.opensuse.org/package/show/home:paulst/scrm

I have no experience in creating Debian packages though, and the configs might need to be improved.

Let me know if you have questions or need help!

Best,
Paul

**Comment by paulstaab** [comment]
Thanks to @terhorst , a brew package for OS X is now available!
