### ISSUE TITLE
Sum of newick tree durations is sometimes longer than the sequence

### ISSUE THREAD

**Issue by paulstaab** [scrm/scrm#82]
Observed in models with a lot of recombination rate changes. Needs a good minimal example.

**Comment by paulstaab** [comment]
Seems this happened only for miss-specified models, when there were sequence rates changes outside of the simulated sequence. I'll add some checks for that.

**Comment by shajoezhu** [comment]
hi @paulstaab , I was wondering what is the miss-specified model? could you give an example?

best
joe

**Comment by paulstaab** [comment]
Something like `scrm 10 1 -r 1 100 -sr 110 2 -T` or `scrm 10 1 -r 1 100 -sr -5 2 -T`

**Comment by paulstaab** [comment]
@shajoezhu Do you think we should throw an error in such cases or rather ignore the invalid rates and print a warning?

**Comment by shajoezhu** [comment]
@paulstaab I think throw an error, and terminate the run would be ideal.

**Comment by gerton** [comment]
Yes — generally I think it is very helpful to throw a meaningful error, rather than silently ignore problems.

BW
G

**Comment by paulstaab** [comment]
Pull request #83 adds the missing checks
