### ISSUE TITLE
Segfault encountered

### ISSUE THREAD

**Issue by terhorst** [scrm/scrm#95]
```scrm 1000 1 -p 6 -t 249.9995 -r 62.49975 499999 -l 10000 -SC abs -seed 123456 -eN 0.0 20.0 -eG 0.0 287.823136624 -eN 0.008 2.0 -eG 0.008 0.0 -T``` results in an instant segfault. Using a smaller sample size like 500 seems to work fine. I am running v1.6.1. From examining the output of scrm_dbg it seems like the issue might a very early coalescence causing a zero branch length. Not sure about this.

**Comment by paulstaab** [comment]
Thanks for the report. That's interesting, could be related to the large growth rate. 

It seems to be working fine for me. What OS are you on? 64/32bit? I guess the seg-fault is occurring whenever you try this, not just for a specific seed?

**Comment by shajoezhu** [comment]
works for me too

**Comment by terhorst** [comment]
Hrm, it does not crash on HEAD. Closing.

**Comment by paulstaab** [comment]
Okay, thanks. I'll try to release version 1.7.0 soon to make sure no one is affected by this.
