### ISSUE TITLE
Failure to build from source on Debian 32 bit

### ISSUE THREAD

**Issue by kdmurray91** [scrm/scrm#98]
Hi,

As part of the Debian packaging process, packages are build (and tests ran) on many architectures. Scrm fails to run unit tests on i386, kfreebsd-i386 and hurd-i386 archs with an identical error.

The debian bug report with more detail is at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811099

I had a quick poke to investigate this, but couldn't find any superficial issue, so I'm forwarding the report upstream.

Cheers,
Kevin

**Comment by paulstaab** [comment]
Hi Kevin,

thanks for reporting this and good to see that the packaging process is on it way. I will look into it, but that will probably take a few days. I will also try to find a continuous integration service that supports 32bit builds to prevent this from happening in the future.

Best,
Paul

**Comment by paulstaab** [comment]
Should be fixed by #99 . There were a couple of unnecessary casts to size_t in the tests that caused them to fail when build with g++ on 32 bit Linux systems.

I will release version 1.7.0 containing the fix tomorrow.

**Comment by kdmurray91** [comment]
Thanks for the investigation Paul! I'll upload the next debian release next week.

**Comment by paulstaab** [comment]
Version 1.7.0 is out @kdmurray91
